[package]
name = "lua-module-calloop"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]
name = "calloop"

[dependencies]
calloop = "0.9.1"
mlua = { version = "0.7.0", features = ["module","lua53"] }

[dev-dependencies]
kukumba = "0.1.0"

