local calloop = require "calloop"

describe("calloop Rust module's", function()
  describe("main loop", function()
    setup(function()
      el = calloop.EventLoop.new()
    end)
    it("can be created", function()
      assert.is_not_nil(el)
    end)
    it("can be run", function()
      assert.is_function(el.get_signal)
      shared_data = el:get_signal()
      assert.is_function(el.run)
      el:run(500, shared_data, function (_shared_data)
            _shared_data:stop()
          end)
    end)
  end)
end)
