local calloop = require "calloop"
local timer = require "calloop.timer"

describe("calloop Rust module's", function()
  describe("timer", function()
    setup(function()
      el = calloop.EventLoop.new()
      tm = timer.Timer.new()
    end)
    it("can be created", function()
      assert.is_table(tm)
      assert.is.equal("timer::Timer", tm._EventSource)
    end)
    it("can produce an EventLoop event", function()
      local th = tm:handle()
      assert.is_table(th)
      th:add_timeout(500, "Timeout reached!")
      handle = el:handle()
      handle:insert_source(tm, function (_shared_data)
            _shared_data:stop()
          end)
      el:run(500, el:get_signal())
    end)
  end)
end)
